# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields:
  github_repo: usetrmnl/byos_laravel
  custom_view: changelog

# override variables
variables:
  trmnl:
    plugin_settings:
      instance_name: "GitHub Repository Insights"
